theme: minima
title: Shamanth Guduru's Portfolio
description: Aspiring Data Analyst | Passionate About Healthcare Analytics

nav:
  - title: "Home"
    url: "/"
  - title: "Certifications"
    url: "/certifications"
  - title: "About"
    url: "/about"
  - title: "Blog"
    url: "/blog"

# Social Links
social_links:
  - icon: "github"
    url: "https://github.com/shamanthguduru"
  - icon: "linkedin"
    url: "https://www.linkedin.com/in/shamanth-guduru/"

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM

# Google Analytics (optional)
google_analytics: "your-google-analytics-id"
favicon: "/assets/images/favicon.ico"

# Default page layout
defaults:
  - scope:
      path: "certifications.md"
    values:
      layout: "page" # Page layout for markdown files


