remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-remote-theme
title: Shamanth Guduru's Portfolio
description: Aspiring Data Analyst | Passionate About Healthcare Analytics| Machine Learning | SQL | R | POWER-BI | Agile | Scrum | SDLC| Excel Dasboards|JASP
