title: "Shamanth Guduru's Portfolio"
description: "Aspiring Data Analyst | Passionate About Healthcare Analytics"
theme: minima

url: "https://shamanthguduru.github.io"
baseurl: ""  # leave this empty

# Navigation settings
nav:
  - title: "Home"
    url: "/"
  - title: "Certifications"
    url: "/Certifications"  # Ensure this page exists or create it
  - title: "About"
    url: "/about"
  - title: "Contact"
    url: "/contact"

# Social Links (update with your real social profiles)
social_links:
  - icon: "github"
    url: "https://github.com/shamanthguduru"
  - icon: "linkedin"
    url: "https://www.linkedin.com/in/shamanth-guduru/"

# Favicon settings
favicon: "/assets/images/favicon.ico"  # Make sure the favicon exists in the correct folder
# Minima Theme Customization
minima:
  skin: dark  # Options: auto, classic, dark, solarized
  date_format: "%b %-d, %Y"
  social_links:
    - { platform: github,  user_url: "https://github.com/shamanthguduru" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/shamanth-guduru/" }
