title: "Shamanth Guduru's Portfolio"
description: "Aspiring Data Analyst | Passionate About Healthcare Analytics"
theme: minima

url: "https://shamanthguduru.github.io"
baseurl: ""  # leave this empty

header_pages:
  - index.md
  - certifications.md
  - about.md
  - contact.md

# Social Links (shows in footer)
social_links:
  github: shamanthguduru
  linkedin: shamanth-guduru

show_excerpts: true  # Shows short descriptions for posts

# Favicon settings
favicon: "/assets/images/favicon.ico"  

# Minima Theme Customization
minima:
  skin: dark  # Options: auto, classic, dark, solarized
  date_format: "%b %-d, %Y"
  social_links:
    - { platform: github,  user_url: "https://github.com/shamanthguduru" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/shamanth-guduru/" }
