title: "Shamanth Guduru's Portfolio"
description: "Aspiring Data Analyst | Passionate About Healthcare Analytics"
theme: minima  # Default theme with dark mode support

url: "https://shamanthguduru.github.io"
baseurl: ""  # Keep this empty

header_pages:
  - index.md
  - certifications.md
  - about.md
  - contact.md

# Social Links (footer icons)
social_links:
  github: shamanthguduru
  linkedin: shamanth-guduru

show_excerpts: true  # Shows post previews

# Minima Theme Customization
minima:
  skin: dark  # Enables dark mode
  date_format: "%b %-d, %Y"
